- name: Submit URLs to IndexNow
        env:
          SITEMAP_URL: "https://www.suzukimedan.my.id/sitemap.xml"
          HOST: "www.suzukimedan.my.id"
          API_KEY: ${{ secrets.INDEXNOW_API_KEY }}

        run: |
          # Ambil URL dari sitemap (maksimal 20 terbaru biar cepat)
          URLS=$(curl -s $SITEMAP_URL | grep -oP '(?<=<loc>).*?(?=</loc>)' | head -n 20)

          # Buat JSON payload
          JSON="{\"host\":\"$HOST\",\"key\":\"$API_KEY\",\"urlList\":["
          for u in $URLS; do
            JSON="$JSON\"$u\","
          done
          JSON="${JSON%,}]}"  # hapus koma terakhir
          
          echo "Payload yang dikirim:"
          echo $JSON

          # Submit ke IndexNow
          curl -s -H "Content-Type: application/json" -d "$JSON" "https://api.indexnow.org/IndexNow"
