name: IndexNow Submit

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Submit URLs to IndexNow
        env:
          SITEMAP_URL: "https://www.suzukimedan.my.id/sitemap.xml"
          HOST: "www.suzukimedan.my.id"
          API_KEY: ${{ secrets.INDEXNOW_API_KEY }}

        run: |
          URL_LIST=$(curl -s "$SITEMAP_URL" | grep -oP '(?<=<loc>).*?(?=</loc>)' | head -n 20)
          
          if [ -z "$URL_LIST" ]; then
            echo "Tidak ada URL yang ditemukan. Proses dihentikan."
            exit 0
          fi
          
          JSON_URLS=$(echo "$URL_LIST" | jq -R . | jq -s .)
          
          PAYLOAD=$(jq -n \
            --arg host "$HOST" \
            --arg key "$API_KEY" \
            --argjson url_list "$JSON_URLS" \
            '{host: $host, key: $key, urlList: $url_list}')
          
          echo "Payload yang akan dikirim:"
          echo "$PAYLOAD"
          
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d "$PAYLOAD" "https://api.indexnow.org/IndexNow")
          
          echo "Status kode respons dari IndexNow: $STATUS_CODE"
          
          # Perbaikan di sini: Cek apakah kode status 200 ATAU 202
          if [ "$STATUS_CODE" -eq 200 ] || [ "$STATUS_CODE" -eq 202 ]; then
            echo "Pengiriman ke IndexNow berhasil."
            exit 0
          else
            echo "Pengiriman ke IndexNow gagal. Status kode: $STATUS_CODE"
            exit 1
          fi
