name: IndexNow Submit

on:
  schedule:
    - cron: "0 */6 * * *"  # Jalan otomatis tiap 6 jam
  workflow_dispatch:        # Bisa dijalankan manual dari tab Actions

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Submit URLs to IndexNow
        env:
          SITEMAP_URL: "https://www.suzukimedan.my.id/sitemap.xml"
          HOST: "www.suzukimedan.my.id"
          API_KEY: ${{ secrets.INDEXNOW_API_KEY }}  # Gunakan secret untuk keamanan

        run: |
          # Ambil 20 URL terbaru dari sitemap
          URL_LIST=$(curl -s $SITEMAP_URL | grep -oP '(?<=<loc>).*?(?=</loc>)' | head -n 20)

          # Buat array JSON dari URL_LIST
          JSON_URLS=$(echo "$URL_LIST" | jq -R . | jq -s .)

          # Buat payload lengkap
          PAYLOAD=$(jq -n \
            --arg host "$HOST" \
            --arg key "$API_KEY" \
            --arg keyloc "https://suzukimedanid.github.io/indexnow-key/$API_KEY.txt" \
            --argjson url_list "$JSON_URLS" \
            '{host: $host, key: $key, keyLocation: $keyloc, urlList: $url_list}')

          echo "Payload yang akan dikirim:"
          echo "$PAYLOAD"

          # Kirim payload ke API IndexNow dan cetak kode status HTTP
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d "$PAYLOAD" "https://api.indexnow.org/IndexNow")
          
          echo "Status kode respons dari IndexNow: $STATUS_CODE"
